replicaCount: 2
image:
  repository: ghcr.io/saraassar/python-getting-started
  tag: a17db65
  pullPolicy: Always
container:
  port: 8000
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30712
