replicaCount: 2

image:
  repository: ghcr.io/saraassar/python-getting-started
  tag: latest
  pullPolicy: Always

container:
  port: 8000

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30712
