replicaCount: 2
image:
  repository: ghcr.io/saraassar/python-getting-started
  tag: 8b5e6e4
  pullPolicy: Always
container:
  port: 8000
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30712
