name: Python CD

on:
  workflow_run:
    workflows:
      - "Python CI"
    types:
      - completed

permissions:
  contents: write

jobs:
  update-gitops:
    name: Update GitOps Repository

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'test' &&
      github.event.workflow_run.event == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(echo '${{ github.event.workflow_run.head_sha }}' | cut -c1-7)" >> $GITHUB_ENV

      - name: Update Helm values.yaml
        run: |
          yq -i '.image.tag = env(IMAGE_TAG)' helm-pyhton/values.yaml

      - name: Verify values.yaml
        run: |
          cat helm-pyhton/values.yaml

      - name: Commit Changes
        run: |
          git add helm-pyhton/values.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore(gitops): update image tag to ${IMAGE_TAG} [skip ci]"

      - name: Push Changes
        run: |
          git push origin test
