name: CI

on:
  push:
    branches:
      - test

permissions:
  contents: write
  packages: write

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Django Tests
        run: |
          python manage.py test

  deploy:
    needs: test
    uses: ./.github/workflows/cd.yaml

